export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const SET_FETCHING_STATE_TRUE = 'SET_FETCHING_STATE_TRUE';
export const SET_NEW_JOKES = 'SET_NEW_JOKES';
export const CLEAR_JOKES_ON_ERROR = 'CLEAR_JOKES_ON_ERROR';
